version: '3.9'

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis
    ports:
      - "16379:6379"

  celery_worker:
    build: .
    command: celery -A orders worker -l info
    depends_on:
      - redis
